# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calculadora.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'calculadora.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63\x61lculadora.proto\x12\x0b\x63\x61lculadora\";\n\x11RequisicaoCalculo\x12\x10\n\x08operacao\x18\x01 \x01(\t\x12\t\n\x01\x61\x18\x02 \x01(\x01\x12\t\n\x01\x62\x18\x03 \x01(\x01\"7\n\x0fRespostaCalculo\x12\x11\n\tresultado\x18\x01 \x01(\x01\x12\x11\n\tdescricao\x18\x02 \x01(\t\"\x11\n\x0fRequisicaoSaude\"/\n\rRespostaSaude\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0e\n\x06versao\x18\x02 \x01(\t2\xa3\x01\n\x0b\x43\x61lculadora\x12H\n\x08\x43\x61lcular\x12\x1e.calculadora.RequisicaoCalculo\x1a\x1c.calculadora.RespostaCalculo\x12J\n\x0eVerificarSaude\x12\x1c.calculadora.RequisicaoSaude\x1a\x1a.calculadora.RespostaSaudeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculadora_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUISICAOCALCULO']._serialized_start=34
  _globals['_REQUISICAOCALCULO']._serialized_end=93
  _globals['_RESPOSTACALCULO']._serialized_start=95
  _globals['_RESPOSTACALCULO']._serialized_end=150
  _globals['_REQUISICAOSAUDE']._serialized_start=152
  _globals['_REQUISICAOSAUDE']._serialized_end=169
  _globals['_RESPOSTASAUDE']._serialized_start=171
  _globals['_RESPOSTASAUDE']._serialized_end=218
  _globals['_CALCULADORA']._serialized_start=221
  _globals['_CALCULADORA']._serialized_end=384
# @@protoc_insertion_point(module_scope)
